# Generated by Django 4.1.4 on 2023-03-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='static/portfolio_project_page/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_img',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
