# Generated by Django 4.1.4 on 2023-03-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0002_project_img_project_name_img_alter_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name_img',
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
