# Generated by Django 4.1.4 on 2023-03-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0003_remove_project_name_img_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
