# Generated by Django 4.1.4 on 2023-03-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0008_alter_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='C:\\Users\\jerem\\PycharmProject\\MyPortfolio\\myportfolio\\portfolio_project_page/static/portfolio_project_page/images/'),
        ),
    ]
