# Generated by Django 4.1.4 on 2023-03-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0011_alter_project_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='img',
            new_name='img_download',
        ),
    ]
