# Generated by Django 4.1.4 on 2023-03-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0012_rename_img_project_img_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img_download',
            field=models.ImageField(upload_to='card_images/'),
        ),
    ]
