# Generated by Django 4.1.4 on 2023-03-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0013_alter_project_img_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=100)),
                ('title_2', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
