# Generated by Django 4.1.4 on 2023-03-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0014_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='img_download',
            field=models.ImageField(default=None, upload_to='card_images/'),
            preserve_default=False,
        ),
    ]
