# Generated by Django 4.1.4 on 2023-03-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0015_delete_project_page_description_page_img_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='id_project',
            field=models.IntegerField(null=True),
        ),
    ]
