# Generated by Django 4.1.4 on 2023-03-28 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0018_alter_page_id_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='id_project',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
