# Generated by Django 4.1.4 on 2023-03-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0019_alter_page_id_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='img_download',
        ),
    ]
