# Generated by Django 4.1.4 on 2023-03-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0020_remove_page_img_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='card_images/'),
        ),
    ]
