# Generated by Django 4.1.4 on 2023-03-28 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0021_page_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='id',
        ),
        migrations.AlterField(
            model_name='page',
            name='id_project',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
