# Generated by Django 4.1.4 on 2023-03-29 06:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0022_remove_page_id_alter_page_id_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
