# Generated by Django 4.1.4 on 2023-03-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0023_alter_page_content_alter_page_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(),
        ),
    ]
