# Generated by Django 4.1.4 on 2023-04-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0024_alter_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
        ),
    ]
