# Generated by Django 4.1.4 on 2023-04-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0026_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>', max_length=100, unique=True),
        ),
    ]
