# Generated by Django 4.1.4 on 2023-04-20 07:10

from django.db import migrations, models
import portfolio_project_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0028_alter_page_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content',
            new_name='contents',
        ),
        migrations.AddField(
            model_name='page',
            name='download_zip_images',
            field=models.FileField(null=True, upload_to='zip_images'),
        ),
    ]
