# Generated by Django 4.1.4 on 2023-04-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0029_rename_content_page_contents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='download_zip_images',
            field=models.FileField(null=True, upload_to='zip_images/'),
        ),
    ]
