# Generated by Django 4.1.4 on 2023-11-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project_page', '0030_alter_page_download_zip_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='download_zip_images',
        ),
    ]
